src/pbrt/gpu/pathintegrator.cpp
`cudaMemAdvise()` and `cudaMemPrefetchAsync()` on GPU devices require those devices to have the `cudaDevAttrConcurrentManagedAccess` attribute set. Since pre-fetching is a performance optimisation and is not mandatory, only enable it when the attribute is set and skip it otherwise to avoid errors (see [this comment][0]).
[0]: https://github.com/mmp/pbrt-v4/issues/20#issuecomment-683182824
=> Avoid pre-fetching when unsupported

CMakeLists.txt, cmake/bin2c_wrapper.cmake
* Rework the compilation to PTX to use the native CMake support via object libraries. This allows using scoped functions like `target_include_directories()` or `target_compile_options()` rather than the previous solution which required changing globally.
* Remove compilation flags that were defined more than once when compiling to PTX.
* Add `PBRT_DEFINITIONS` to the compilation flags when compiling to PTX, to solve the last bits of #27.
* Since the compilation to PTX no longer requires global includes, include OptiX using `target_include_directories()`.
=> Rework PTX compilation

CMakeLists.txt
Solving the configuration error raised because of the removed file `util/shuffle.h` (commit 8578c81).
=> Removing previously deleted source file from CMakeLists.txt.

src/pbrt/media.cpp
This fixes an issue where pbrt can not find NanoVDB files that are specified with a relative path.
This fix would resolve the following scenario: 
`pbrt scenes/test_file.pbrt`
Where `test_file.pbrt` contains:
```
MakeNamedMedium "foggy" "string type" "nanovdb" "string filename" [ "../../vdbs/test.nvdb" ]
```
=> Wrap nvdb filename parameter with ResolveFilename()

src/pbrt/shapes.cpp
pbrt-v4 will crash when rendering a ribbon curve where both the start and end normal are the same value. When the angle between these two normals are 0 there is a division by 0 here -
https://github.com/mmp/pbrt-v4/blob/d6be103baa4e2c18c80af78662dce18e7f8b407e/src/pbrt/shapes.cpp#L471
Which later leads to a multiply by inf here -
https://github.com/mmp/pbrt-v4/blob/d6be103baa4e2c18c80af78662dce18e7f8b407e/src/pbrt/shapes.cpp#L650-L652
This fix avoids these values by simply using the ribbon curve's start normal as the nHit would be the same along the curve.
A test case which causes the crash is provided here -
[curve_crash.zip](https://github.com/mmp/pbrt-v4/files/5287539/curve_crash.zip)
=> Avoid division by zero with flat ribbon curves

src/pbrt/shapes.cpp
In pbrt-v4 when we have a straight curve we can run into a case where L0 == 0
https://github.com/mmp/pbrt-v4/blob/d6be103baa4e2c18c80af78662dce18e7f8b407e/src/pbrt/shapes.cpp#L576-L582
When L0 is 0, a subsequent check within Log fails.
https://github.com/mmp/pbrt-v4/blob/d6be103baa4e2c18c80af78662dce18e7f8b407e/src/pbrt/util/math.h#L343
To avoid this issue, this fix avoids computing the refinement level and instead sets the max refinement depth to 0.
Attached is a sample scene which causes a fatal error
[straight_curve.zip](https://github.com/mmp/pbrt-v4/files/5287745/straight_curve.zip)
=> Avoid refinement depth calc for straight curves

CMakeLists.txt, cmake/bin2c_wrapper.cmake, src/ext/CMakeLists.txt
Since we have a CMake target, we can do scoped include directories.
Remove duplicate compile flags, and also add compile definitions which
enables PBRT to compile on Windows for Pascal-architecture cards.
Compared to commit a685e0205e433cefe99e13ab36ca340eb7bdfdf6, this also
* changes the dependency to be directly on the library rather than some of its object file;
* adds a missing dependency on several generated header files;
* avoids passing `/D _CRT_SECURE_NO_WARNINGS` to nvcc;
* removes compiler flags that are part of the regular CUDA flags.
=> Rework the compilation to PTX and embedding

CMakeLists.txt
CUDA integration in Visual Studio seems broken as even if "Use Host Preprocessor Definitions" is checked, the host preprocessor definitions are still not used when compiling device code.
I tried creating a new CUDA project using the CUDA project templates in Visual Studio, to avoid having CMake in the equation, and experienced the same issue there so it really seems like CMake is setting up the project properly but the Visual Studio CUDA integration is ignoring the "Use Host Preprocessor Definitions" option.
First you can see that host definitions are marked for usage with device code
However despite that, the host definitions do not show up on the command line when compiling device code but do only for host code
To work around that, define the macros using --define-macro to avoid CMake …
=> Specify macros as compile flags with Visual Studio

src/ext/flip/flip.cpp
_USE_MATH_DEFINES needs to be defined, right before cmath is included, on Windows for M_PI to be available.
Fixes #66 ("ꟻLIP compilation failure on Windows due to undefined symbol M_PI")
=> Fix flip build on windows

src/pbrt/media.h
Note: the volume files converted from OpenVDB to NanoVDB format need to be
converted again or it will cause GridMetadata errors.
=> Upgrading to latest nanovdb version.

CMakeLists.txt, src/pbrt/gpu/accel.cpp
Just a few improvements regarding OptiX
* showing the version as major.minor.micro,
* and using a higher log level in debug builds
and CMake
* ensuring that embedding of the PTX always run after the PTX is re-generated,
* and updating the comment of the embedding command to reflect that it only does embedding
=> Small improvements

cmake/checkcuda.cu
Small fix to cudacheck, the integer divide was rounding down the compute capability to just the major version. Probably didn't impact too many users unless they were running compute capability 5.3 devices.
Thank you for all your work on pbrt, really looking forward to the next edition of the book!
=> Fix compute capability calculation in cudacheck

src/ext/CMakeLists.txt
There is a cmake error when trying to build on Windows using cmake version 3.17.3. Running cmake generates the following error for ILMBASE:
> -- Configure ILMBASE Version: 2.5.3 Lib API: 25.0.2
> CMake Warning (dev) at src/ext/openexr/IlmBase/config/IlmBaseSetup.cmake:56 (option):
>   Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
>   --help-policy CMP0077" for policy details.  Use the cmake_policy command to
>   set the policy and suppress this warning.
> 
>   For compatibility with older versions of CMake, option is clearing the
>   normal variable 'BUILD_SHARED_LIBS'.
> Call Stack (most recent call first):
>   src/ext/openexr/IlmBase/CMakeLists.txt:35 (include)
> This warning is for project developers.  Use -Wno-dev to suppress it.
When trying to building the …
=> Fixes cmake policy CMP0077 build error on windows

CMakeLists.txt, src/pbrt/util/check.h
Various improvements to the CMake configuration, focused around replacing variables with interface libraries for collecting flags and definitions, as the latter allows generator expressions which can be used to only apply flags for certain compilers or languages.
Currently only the warning suppression flags are processed that way, allowing them to be used once again even when using the CUDA backend.
=> CMake improvements

src/ext/CMakeLists.txt
I noticed on Ubuntu 20.04, CMake 3.16.3, and dc107ca the various IlmBase libraries were being compiled as shared instead of static.
This also syncs up with the comment from @povmaniaco here - https://github.com/mmp/pbrt-v4/pull/95#issuecomment-755226187
When building with CMake 3.16.3 or 3.19.2 I see this in output:
```
CMake Warning (dev) at src/ext/openexr/IlmBase/config/IlmBaseSetup.cmake:56 (option):
Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
--help-policy CMP0077" for policy details.  Use the cmake_policy command to
set the policy and suppress this warning.
For compatibility with older versions of CMake, option is clearing the
normal variable 'BUILD_SHARED_LIBS'.
```
I came across these comments about policies being unset: …
=> Apply CMake CMP0077 policy in a different way

CMakeLists.txt
When building `checkcuda` nvcc might not be on the $PATH, instead rely on the CMake variable CMAKE_CUDA_COMPILER which will be defined by this point in the CMakeLists.txt
This will fix the following cmake error
```
-- Found CUDA: /usr/local/cuda (found version "11.2") 
-- Found CUDA: 11.2
-- The CUDA compiler identification is NVIDIA 11.2.67
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda-11.2/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
CMake Error at CMakeLists.txt:206 (message):
```
This error is due to the following failing
```
execute_process (COMMAND ${CHECK_CUDA_OUTPUT_EXE}
RESULT_VARIABLE CUDA_RETURN_CODE
OUTPUT_VARIABLE CHECK_CUDA_OUTPUT)
```
As a …
=> Use CMAKE_CUDA_COMPILER instead of nvcc

src/pbrt/cmd/imgtool.cpp
Two small changes to imgtool
First change is to add the "info" option to the help.
For the second change, I keep forgetting to make a note of what makesky settings I used when creating a envmap. I figured the easiest solution is to record the parameter values in the image metadata.
`imgtool makesky --outfile blah.exr`
`imgtool info blah.exr `
```
blah.exr:
resolution (2048, 2048)
pixel format: Float
color space : ACES
full resolution (2048, 2048)
pixel bounds (0, 0) - (2048, 2048)
"makesky.albedo": [ "0.500000" ]
"makesky.elevation": [ "0.174533" ]
"makesky.turbidity": [ "3.000000" ]
Channels:
B: min            0 max      5222.34 avg     0.057673 (0 infinite, 0 not-a-number)
G: min            0 max      10177.2 avg    0.0763236 (0 infinite, 0 not-a-number)
R: min            0 max …
```
=> imgtool, update info help along with adding makesky metadata

src/pbrt/parser.cpp, src/pbrt/util/file.cpp, src/pbrt/util/file.h
This PR adds support for reading gzipped scene files, directly or through Include or Import statements.
The main motivator was dealing with very large uniformgrid volumes. As a contrived example, a scene file with a 512^3 voxel array with values of 1 results in a 257MB file. But compressed it is only 256KB.
As a bonus pbrt-v4 already has zlib as an external resource so this change doesn't add a new dependency.
Lastly, through gzerror(...) better error messages can be generated to help relay causes of errors, however in an attempt to keep the code reasonably straight forward I omitted all but the most basic error conditions.
This was tested on Linux and Windows.
=> Add support for reading gzip scene files

src/pbrt/lightsamplers.cpp, src/pbrt/lightsamplers.h
Howdy,
I noticed when rendering with at least one non-infinite light and multiple infinite lights that some of the infinite lights were not being sampled.
I believe this has to do with how `u` is being scaled. Instead of multiplying `u` by `pInfinite` we should be dividing so that `u` is between 0 and 1.
https://github.com/mmp/pbrt-v4/blob/43ce733ea0775a71045c7ccfada4d855901f2230/src/pbrt/lightsamplers.h#L273-L282
This affects the Path and VolPath integrators when using the BVH or Exhaustive light sampling strategies. 
```
Film "rgb"
"string filename" [ "light_bug.exr" ]
"integer yresolution" [ 256 ]
"integer xresolution" [ 256 ]
PixelFilter "gaussian"
"float xradius" [ 2 ]
"float yradius" [ 2 ]
Sampler "zsobol"
"integer pixelsamples" [ 128 ]
Integrator "volpath"
"integer maxdepth" [ 5 ] …
```
=> Fix scaling of u when sampling infinite lights

src/pbrt/gpu/optix.cu, src/pbrt/wavefront/intersect.h
Two small fixes to the debug printing. Some variables were removed or renamed in 59b5988 and 24c6ef5 and the debug prints got out of sync.
=> Fixes to PBRT_DBG_LOGGING

src/pbrt/base/medium.h, src/pbrt/media.cpp, src/pbrt/media.h
_**Note**: The is PR is a Draft of an implementation, if the idea makes sense for pbrt-v4 (especially at this late stage) then I'm happy to tidy up the code, otherwise we can reject it._
Uniform Grid's `rgb density.rgb` option is a difficult interface for specifying coloured volumetrics. This is due to rgb values being used both for sigma_a and sigma_s.
https://github.com/mmp/pbrt-v4/blob/77d367204ad7c73eb5072c62f5e6f12604f0574d/src/pbrt/media.h#L386-L391
An rgb density value of (1,0,0) means you'll be scattering and absorbing red light in the cross section. The absorption of the red light results in a cyan being transmitted.
The following are some renders of a density.rgb  setup, where the rgb values of each smoke plume start at red on the left and go purple on the right. In other words, …
=> Implementation to Provide RGB Grid Values for sigma_a and sigma_s

src/pbrt/media.cpp
Fixed a missing %s in HomogeneousMedium::ToString()
=> Add missing string format in HomogeneousMedium

exporters/Blender/Readme.md
The link in the readme that points to the addon zip archive was wrong.
I updated this and also point directly to the Pbrt-v4 branch so that it's less confusing for the users.
=> Updated links in readme for blender exporter.

src/pbrt/parser.cpp, src/pbrt/scene.cpp
Expose RenderingCoordinateSystem as a scene file Option (to complement the --render-coord-sys arg).
This also provides a workaround for #206 in how instances are interpolated.
=> Add rendercoordsys as a scene Option

src/pbrt/materials.cpp
Prevent a NaN condition when CoatedConductor has a reflectance of 1.  This PR updates CoatedConductor to match Conductor's behaviour.
Existing check in ConductorMaterial -
https://github.com/mmp/pbrt-v4/blob/24d5abf6f27d11264028da1b8b57299a0c3aa03c/src/pbrt/materials.h#L504-L505
```
Film "rgb"
"integer yresolution" [ 512 ]
"integer xresolution" [ 512 ]
"string filename" [ "pbrt.exr" ]
PixelFilter "gaussian"
"float yradius" [ 2 ]
"float xradius" [ 2 ]
Sampler "zsobol"
"integer pixelsamples" [ 128 ]
Integrator "volpath"
Accelerator "bvh"
Rotate -30 1 0 0
Translate 0 -1.5 3
Camera "perspective"
"float screenwindow" [ -1 1 -1 1 ]
"float fov" [ 50 ]
WorldBegin
AttributeBegin
Rotate 90 1 0 0
LightSource "distant"
AttributeEnd
MakeNamedMaterial "/mat/pbrt_material_coatedconductor1"
"string type" …
```
=> Prevent NaN when CoatedConductor reflectance is 1

src/pbrt/wavefront/integrator.cpp
I noticed an assert failing when rendering with an instance object with a medium. In debug mode the following assert was triggering
https://github.com/mmp/pbrt-v4/blob/24d5abf6f27d11264028da1b8b57299a0c3aa03c/src/pbrt/wavefront/intersect.h#L58
This is due to `mediumSampleQueue` never being allocated because `haveMedia` was false. 
https://github.com/mmp/pbrt-v4/blob/24d5abf6f27d11264028da1b8b57299a0c3aa03c/src/pbrt/wavefront/integrator.cpp#L252-L253
While the shapes and animated shapes were checked for mediums the instance definitions were not.
https://github.com/mmp/pbrt-v4/blob/24d5abf6f27d11264028da1b8b57299a0c3aa03c/src/pbrt/wavefront/integrator.cpp#L95-L102
This PR adds checks for the shapes and animated shapes in the instance definitions.
```
Film "rgb"
"integer yresolution" [ 256 ] …
```
=> In Wavefront Integrator check instance defintions for mediums

.gitmodules
Add `.git` to the double-conversion and zlib submodules URLs.
=> Make submodule URLs consistent

src/pbrt/film.cpp
Hi,
Cool that you've added Spectral EXR support! I have a slight issue on my side when I try to open the file with SpectralViewer (RGB layers are correct).
The spectral layers are not correctly written in the Spectral Film. It seems the error comes from the creation of the main buffer: the address is offset by `NSpectrumSamples` (the number of multiplexed wavelengths in one ray?) instead of `nBuckets`.
Cheers.
=> Fix address offsets in Spectral Film 

src/pbrt/util/gui.cpp
On high DPI monitors, the framebuffer has a different size from the window and only the top-left quarter of pixels are drawn in the interactive mode. This PR corrects the scaling factors passed to `glPixelZoom` to fix this issue.
=> Fix interactive display when window size and framebuffer size mismatch

src/pbrt/cpu/integrators.cpp
* Tested the Cornell Box scene on [Benedikt's page](https://benedikt-bitterli.me/resources/).
* old
* new
* new v.s. GT
=> Fix process of directly visible light for LightPathIntegrator

src/pbrt/util/taggedptr.h, src/pbrt/util/taggedptr_test.cpp
Hi,
I think there might be an issue in the implementaion of `Dispatch()` and `DispatchCPU()` in taggedptr.h:
https://github.com/mmp/pbrt-v4/blob/bc25558763649eb25052a29299594d62c67ed39f/src/pbrt/util/taggedptr.h#L562-L586
https://github.com/mmp/pbrt-v4/blob/bc25558763649eb25052a29299594d62c67ed39f/src/pbrt/util/taggedptr.h#L615-L640
Note that template parameter pack `Ts` here could accept zero or more template arguments, so these two functions will be ambiguous.
So once I have a handle struct that inherits `TaggedPointer` instantiated with 8x types:
```cpp
struct HandleWithEightConcreteTypes : public TaggedPointer<IntType<0>, IntType<1>, IntType<2>, IntType<3>,
IntType<4>, IntType<5>, IntType<6>, IntType<7>> {
using TaggedPointer::TaggedPointer;
int func() {
auto f = [&](auto ptr) { …
```
=> Fix TaggedPointer ambiguous `DispatchCPU()` call issue when instantiated with 8x types.

CMakeLists.txt
This way it doesn't has to be set in CMakeCache.txt every time the
repository is checked out.
=> Read Optix path from environment.

src/pbrt/cameras.cpp
=> Only resolve aperture as a file if not a builtin name

src/pbrt/util/file.cpp
One approach to solving issue #280
ResolveFilename() calls filesystem::path::make_absolute() which does a file stat and errors if the file doesn't exist. This commit adds an additional check and only adds the search path if the resulting file exists. Otherwise it leaves the path alone.
=> Check to see if a filepath exists before making absolute

src/ext/CMakeLists.txt
Build with Clang 14 under Windows show this error
```
clang-14: error: no such file or directory: '/D'
clang-14: error: no such file or directory: 'PTEX_STATIC'
```
This commit fix this and is also OK for MSVC
=> Avoid Clang 14 error compiling under Windows

src/pbrt/gpu/denoiser.cpp
During experiment with the PBRT build failed due to parameter type mismatch.
nVIDIA OptiX-SDK-7.5.0
F36
GCC Version 12.1.1
=> Corrected denoiseAlpha parameter type

src/pbrt/cmd/imgtool.cpp
This patch fix a issue using denoise because a Variance channel names exposed here: https://github.com/mmp/pbrt-v4/issues/300
=> Fix denoise issues

src/pbrt/gpu/cudagl.h
`./pbrt --gpu --interactive ~/src/pbrt-v4-scenes/bmw-m6/bmw-m6.pbrt` crashes under Wayland with
```
[ tid 20700 @     0.000s gpu/cudagl.h:356 ] FATAL GL interop is only available on display device.
(./pbrt                                  )	0x0x5653c36d980a - pbrt::PrintStackTrace() + 0x3a
(./pbrt                                  )	0x0x5653c36d9ab1 - pbrt::CheckCallbackScope::Fail() + 0x21
(./pbrt                                  )	0x0x5653c373d9e2 - pbrt::LogFatal(pbrt::LogLevel, char const*, int, char const*) + 0xf2
(./pbrt                                  )	0x0x5653c3a7c059 - pbrt::CUDAOutputBuffer<pbrt::RGB>::CUDAOutputBuffer(int, int) + 0x4e9
(./pbrt                                  )	0x0x5653c3a7799a - pbrt::GUI::GUI(std::__cxx11::basic_string<char, std::char_traits<char>, …
```
=> Fix crash on Wayland.

src/pbrt/bxdfs.cpp
Addresses #313
This provides a check similar to the one used in pbrt-v3
https://github.com/mmp/pbrt-v3/blob/aaa552a4b9cbf9dccb71450f47b268e0ed6370e2/src/core/reflection.cpp#L660
=> Avoid NaNs when the BSDFSample's pdf is 0.

CMakeLists.txt
This directive silences many annoying and perhaps unused warning messages under MacOS arm64 about that a few of printf's are now deprecated
=> Silent build warnings about deprecated 'snprintf'

src/pbrt/gpu/aggregate.cpp
I didn't test this yet for both old/new version of optix, or anywhere but windows 10/VC 2019, but it does fix it for me locally. I can test more thoroughly later tonight.
Is #defining the function name fine or do you prefer avoiding that method?
=> Address compile issue with macro expansion for using optixModuleCreate or optixModuleCreateFromPTX

CMakeLists.txt
Silence a MSVC warning 4146 caused by NanoVDB code when a unary minus operator is applied to an unsigned type.
=> Silent warning in VDB dependecies

src/pbrt/pbrt_lldbdataformatters.py
1. Load Manually (everytime)
use lldb command 'command script import [PATH]/pbrt_lldbdataformatters.py' (without the quotes)
2. Load Automatically (add to ~/.lldbinit)
1) create ~/.lldbinit file if there isn't
2) open ~/.lldbinit
3) add 'command script import [PATH]/pbrt_lldbdataformatters.py' to the file (without the quotes)
4) restart xcode
-  May not work well on some type, such as **pstd::optional<SquareMatrix<2>>**
=> LLDB DataFormatters (Debug Visualizer) 

src/pbrt/materials.cpp
This takes the incident index of refraction into account when setting the relative index of refraction for coated conductors.
fixes #342
=> Take the incident `IOR` into account for the `CoatedConductorMaterial`

src/pbrt/util/math.h
`src/pbrt/util/math.h`: url `http://rnc7.loria.fr/louvet_poster.pdf` is broken, use `https://www-pequan.lip6.fr/~graillat/papers/posterRNC7.pdf` instead
=> fix broken url

src/pbrt/materials.h
This change fix a error on Hair material when the upper value for 'beta_m' or 'beta_n' is greatest than 1.0.
More details in this bug report: https://github.com/mmp/pbrt-v4/issues/338
=> Fix fatal error on Hair material

src/pbrt/film.cpp
Updated some channel names in G-Buffer following the naming policy for EXR multilayer. More details here : https://github.com/mmp/pbrt-v4/issues/355
=> Update a few channels names for G-Buffer

src/pbrt/gpu/aggregate.cpp, src/pbrt/gpu/denoiser.cpp
As per the [release notes](https://developer.nvidia.com/downloads/designworks/optix/secure/8.0.0/optix_release_notes_8.0_01.pdf) of OptiX 8, some APIs have been changed, which break the compilation:
1. The flag `OPTIX_EXCEPTION_FLAG_DEBUG` has been removed;
2. `OptixDenoiserAlphaMode` was moved from `OptixDenoiserParams` to `OptixDenoiserOptions`.
This PR adds version guards for these changes to make PBRT-v4 compatible with OptiX 8.
=> Compatibility with OptiX 8

src/pbrt/util/spectrum_test.cpp
Removes a 10x multiplier on the maximum value in the MaxValue test for RgbUnboundedSpectrum. The 10x multiplier makes the check unnecessarily lax; the evaluations on the various lambdas below it pass without the multiplier applied.
=> Constrain max value test further for unbounded

src/pbrt/util/mesh.h
This patch attempts to fix the bug when displacing plymesh containing a quad.
The bug only exists when running with CPU only.
Example scene (taken from [pbrt.org](https://pbrt.org/fileformat-v4#example)):
```
LookAt 3 4 1.5  # eye
.5 .5 0  # look at point
0 0 1    # up vector
Camera "perspective" "float fov" 45
Sampler "halton" "integer pixelsamples" 128
Integrator "volpath"
Film "rgb" "string filename" "simple.png"
"integer xresolution" [400] "integer yresolution" [400]
WorldBegin
LightSource "infinite" "rgb L" [ .4 .45 .5 ]
LightSource "distant"  "point3 from" [ -30 40  100 ]
"blackbody L" 3000 "float scale" 1.5
Texture "white"
"float" "imagemap"
"string filename" "white.png"
AttributeBegin
Material "coateddiffuse"
Shape "plymesh"
"string filename" "sphere.ply"
"texture displacement" …
```
=> Fix displacement for plymesh

src/pbrt/film.cpp
This pointer should be incremented by nBuckets, and not NSpectrumSamples.
This should fix issue #450.
=> Increment splatBuffer pointer by correct amount

src/pbrt/cpu/integrators.cpp
Small changes allow SPPM to converge to the correct image for animated scenes. Before. Rays and photons were individually sampling a separate timestamp leading to many inconsistencies, see #440. This approach can not work without significant changes (e.g. implementing a time kernel). Using a single timestamp per iteration and using it for all rays and photons of that iteration instead provides a straightforward solution to this problem with minimal additions. Because of the numerous iterations/samples of SPPM, it reliably converges to the correct result without any sampling artifacts. I am fairly certain that this is also how they did it in the [original paper](http://graphics.ucsd.edu/~henrik/papers/sppm/stochastic_progressive_photon_mapping.pdf).
Image with Path Tracer Integrator:
Image …
=> Fixing Time Sampling/Motion Blur for SPPM

src/pbrt/util/float.h
This confused me for a couple minutes, so thought I would throw up a PR to update these comments.
```
#ifdef PBRT_IS_GPU_CODE
< GPU Code >
#else  // GPU
< CPU Code >
#endif
```
I think the comment next to the else is supposed to say "CPU" since that is the block that is happening here. 
```
#ifdef PBRT_IS_GPU_CODE
< GPU Code >
#else  // CPU
< CPU Code >
#endif
```
This PR simply updates those comments.
=> Update float.h "# else // GPU" comments

CMakeLists.txt
The related open issue: #467 
* Adds a post-configuration step that explicitly installs `zlibstatic` into the `Ptex` export set.
* Prevents "target not in any export set" errors during the installation stage.
* Leaves the existing Ptex submodule files unmodified, preserving upstream compatibility.
* Verified on Windows 10 with Visual Studio 2022.
=> Fix CMake build error on Windows 10 by exporting zlibstatic alongside Ptex_static

.gitmodules, CMakeLists.txt, src/ext/CMakeLists.txt
Use the "modern" cmake way of naming/passing along targets; as a bonus, this lets us bump the version of openexr we ship as a submodule to be the most recent release.
Fixes #478, which was due to pbrt not handling having a modern version of openexr installed locally.
=> Redo cmake/OpenEXR integration
